name: gestion_condominios
description: Aplicacion movil Flutter para gestion de condominios
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.0
  shared_preferences: ^2.3.2
  image_picker: ^1.1.0
  file_picker: ^8.1.7
  flutter_hooks: ^0.21.3+1
  provider: ^6.1.2
  cupertino_icons: ^1.0.8
  shimmer: ^3.0.0
  lottie: ^3.1.0
  flutter_staggered_animations: ^1.1.1
  animated_list_plus: ^0.5.0
  rive: ^0.13.20
  url_launcher: ^6.3.0
  local_auth: ^2.3.0
  flutter_secure_storage: ^9.2.4
  intl: ^0.20.2
  sentry_flutter: ^9.14.0
  vibration: ^3.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - lib/assets/

  fonts:
    - family: TT Hoves Pro Trial
      fonts:
        - asset: lib/assets/fonts/TT Hoves Pro Trial Regular.ttf
          weight: 400
        - asset: lib/assets/fonts/TT Hoves Pro Trial Medium.ttf
          weight: 500
        - asset: lib/assets/fonts/TT Hoves Pro Trial Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/TT Hoves Pro Trial Black.ttf
          weight: 900
