<?php

return [
    'APP_ENV' => 'local',
    'APP_DEBUG' => '1',
    'DB_HOST' => 'localhost',
    'DB_NAME' => 'database_name',
    'DB_USER' => 'database_user',
    'DB_PASS' => 'database_password',
    'DB_PORT' => '5432',
    'CORS_ALLOWED_ORIGINS' => 'http://localhost:3000,http://127.0.0.1:3000',
    'TOKEN_TTL_MINUTES' => '43200',
    'TOKEN_REFRESH_THRESHOLD_MINUTES' => '10',
    'TWO_FACTOR_CODE_TTL_MINUTES' => '5',
    'TWO_FACTOR_MAX_ATTEMPTS' => '3',
    'TWO_FACTOR_RESEND_COOLDOWN_SECONDS' => '60',
    'TWO_FACTOR_REQUEST_WINDOW_SECONDS' => '900',
    'TWO_FACTOR_REQUEST_MAX_PER_USER' => '5',
    'TWO_FACTOR_REQUEST_MAX_PER_IP' => '20',
    'TWO_FACTOR_DEBUG_EXPOSE_CODE' => '1',
    'DEV_LOGIN_BYPASS' => '0',
    'DEV_LOGIN_BYPASS_EMAILS' => 'test@example.com',
    'AVATAR_MAX_BYTES' => '2000000',
    'MAIL_APP_NAME' => 'Vecinus',
    'MAIL_FROM_EMAIL' => 'no-reply@example.com',
    'MAIL_FROM_NAME' => 'Vecinus',
    'MAIL_OTP_SUBJECT_PREFIX' => 'Vecinus',
    'SMTP_HOST' => 'mail.example.com',
    'SMTP_PORT' => '465',
    'SMTP_USERNAME' => 'no-reply@example.com',
    'SMTP_PASSWORD' => 'smtp_password',
    'SMTP_SECURE' => 'ssl',
    'SMTP_TIMEOUT_SECONDS' => '15',
    'EVIDENCE_MAX_BYTES' => '5000000',
];
